name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Pull lomiri source
        run: |
          yes '' | pmbootstrap init
          cd `pmbootstrap config aports`
          git checkout feature/lomiri
      - name: Build
        run: |
          mv `pmbootstrap config aports`/lomiri/lomiri .
          pmbootstrap build accountsservice-ubuntu qtmir repowerd --arch x86_64
          pmbootstrap build lomiri-system-settings lomiri postmarketos-ui-lomiri --arch x86_64
