name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Pull lomiri source
        run: |
          yes '' | pmbootstrap init
          cd `pmbootstrap config aports`
          git checkout feature/lomiri
      - name: Build postmarketos-ui-lomiri
        run: |
          mv `pmbootstrap config aports`/lomiri/lomiri .
          pmbootstrap build accountsservice-ubuntu qtmir repowerd lomiri-system-settings --arch x86_64
          mv lomiri `pmbootstrap config aports`/lomiri/
          pmbootstrap build lomiri postmarketos-ui-lomiri --arch x86_64
      - name: Build other packages
        run: |
          pmbootstrap build fairphone-fp4 ubuntu-themes qqc2-suru-style platform-api lomiri-terminal-app lomiri-qmltermwidget biometryd lomiri-notifications --arch x86_64
